/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'yuexinmiao'
 * Target:  'yuexinmiao'
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File:
 */
#define CMSIS_device_header "NUC131.h"



#endif /* RTE_COMPONENTS_H */
